name: Summarize Issue Text

on:
  issues:
    types: [opened]

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
    - name: Get issue text
      id: get_text
      uses: actions/github-script@v3
      with:
        script: |
          const issue = context.payload.issue;
          const text = issue.body;
          core.setOutput("text", text);

    - name: Format request body
      id: format_body
      run: echo '{"text":"${{ steps.get_text.outputs.text }}"}' > request_body.json

    - name: Send request
      id: send_request
      run: curl -X POST -d @request_body.json https://webhook.site/a2d04d96-f9e7-4a46-84a9-6ab641f45226

    - name: Get response
      id: get_response
      run: echo "${{ steps.send_request.outputs.stdout }}"

    - name: Add response as a comment
      uses: actions/github-script@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        script: |
          const response = steps.get_response.outputs.stdout;
          const octokit = new github.GitHub(process.env.GITHUB_TOKEN);
          octokit.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.name,
            issue_number: context.payload.issue.number,
            body: response
          });
